name: Pull Request Workflow

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  run-test:
    uses: ./.github/workflows/test_and_build.yaml
    secrets: inherit